/*
 * One-shot: regenerate data/cities.ts from the GeoNames cities15000 dump.
 *
 * Source files (gitignored, in data/_cache/):
 *   - cities15000.txt (unzipped from cities15000.zip)
 *   - countryInfo.txt
 *
 * Downloads:
 *   https://download.geonames.org/export/dump/cities15000.zip
 *   https://download.geonames.org/export/dump/countryInfo.txt
 *
 * Usage:
 *   npx tsx scripts/generate-cities-data.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const CACHE_DIR = join(process.cwd(), "data", "_cache");
const OUT_FILE = join(process.cwd(), "data", "cities.ts");

type CityTuple = [
  name: string,
  countryCode: string,
  countryName: string,
  lat: number,
  lng: number,
  population: number,
];

function loadCountryNames(): Map<string, string> {
  const raw = readFileSync(join(CACHE_DIR, "countryInfo.txt"), "utf8");
  const map = new Map<string, string>();
  for (const line of raw.split(/\r?\n/)) {
    if (!line || line.startsWith("#")) continue;
    const parts = line.split("\t");
    const iso = parts[0];
    const name = parts[4];
    if (iso && name) map.set(iso, name);
  }
  return map;
}

function loadCities(countryNames: Map<string, string>): CityTuple[] {
  const raw = readFileSync(join(CACHE_DIR, "cities15000.txt"), "utf8");
  const out: CityTuple[] = [];
  for (const line of raw.split(/\r?\n/)) {
    if (!line) continue;
    const parts = line.split("\t");
    const name = parts[1];
    const lat = Number.parseFloat(parts[4]);
    const lng = Number.parseFloat(parts[5]);
    const cc = parts[8];
    const population = Number.parseInt(parts[14], 10);
    if (!name || !cc || Number.isNaN(lat) || Number.isNaN(lng)) continue;
    const countryName = countryNames.get(cc) ?? cc;
    out.push([
      name,
      cc,
      countryName,
      Math.round(lat * 10000) / 10000,
      Math.round(lng * 10000) / 10000,
      Number.isFinite(population) ? population : 0,
    ]);
  }
  return out;
}

function emit(tuples: CityTuple[]): string {
  const lines = tuples.map((t) => {
    const name = JSON.stringify(t[0]);
    const cc = JSON.stringify(t[1]);
    const cn = JSON.stringify(t[2]);
    return `  [${name},${cc},${cn},${t[3]},${t[4]},${t[5]}]`;
  });
  return [
    "// AUTO-GENERATED by scripts/generate-cities-data.ts",
    "// Source: GeoNames cities15000 (https://download.geonames.org/export/dump/)",
    "// Licensed CC BY 4.0 — https://creativecommons.org/licenses/by/4.0/",
    "// Do not edit by hand. Regenerate with: npx tsx scripts/generate-cities-data.ts",
    "",
    "export type CityTuple = [",
    "  name: string,",
    "  countryCode: string,",
    "  countryName: string,",
    "  lat: number,",
    "  lng: number,",
    "  population: number,",
    "];",
    "",
    "export const cities: CityTuple[] = [",
    lines.join(",\n"),
    "];",
    "",
  ].join("\n");
}

function main() {
  const countryNames = loadCountryNames();
  const tuples = loadCities(countryNames);
  tuples.sort((a, b) => b[5] - a[5]);
  writeFileSync(OUT_FILE, emit(tuples), "utf8");
  console.log(`Wrote ${tuples.length} cities to ${OUT_FILE}`);
}

main();
